# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3m-MvFhxc0a3pJy7SzjxpxfhR6XrmKb
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np 

data = pd.read_csv("ML Case Study - Data.csv")
for i,k in enumerate(data["Experience"]):
    if k < 0:
        data["Experience"][i] = 0

data.drop("ZIP Code", axis = 1, inplace= True)
data.drop("ID", axis = 1, inplace= True)

x = data.loc[:,['Age', 'Experience', 'Income', 'Family', 'CCAvg', 'Education',
       'Mortgage', 'Securities Account', 'CD Account',
       'Online', 'CreditCard']]
y = data["Personal Loan"]
print(x.shape,y.shape)
dic = {0:0,1:1}
for k in y:
    dic[k] +=1

from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test = train_test_split(x,y,test_size = 0.3,random_state=7)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
rbf_clf = RandomForestClassifier(n_estimators=100,max_depth = None)
rbf_clf.fit(X_train, Y_train)
Y_pred = rbf_clf.predict(X_test)
print(rbf_clf.score(X_test, Y_test),f1_score(Y_test,Y_pred))

import pickle
pickle.dump(rbf_clf,open("rbf_clf.pkl","wb"))
model = pickle.load(open('rbf_clf.pkl', 'rb'))

print(model.score(X_test,Y_test))

